require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '14.0'

target 'ChessAscend' do
  config = use_native_modules!

  # Ensure Hermes generates debug symbols
use_react_native!(
  :hermes_enabled => true,
  :fabric_enabled => false,
  # Ensures Hermes is built in Release mode and includes debugging symbols
  :production => true,
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'Permission-Camera', :path => "#{permissions_path}/Camera/Permission-Camera.podspec"

  target 'ChessAscendTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
  end
end
